export interface NoteEntry {
  id: string
  href: string
  title: string
  subject: NoteSubject
  tags: string[]
  desc: string
  /** 筆記分類；省略視為「考點筆記」。「快速複習」放純表格速查/總表。 */
  category?: NoteCategory
  /** 大分類/章：把相關筆記歸在同一標題下（如「細胞學」「量子論與原子結構」）。省略＝不分組。 */
  group?: string
}

export type NoteSubject = '化學' | '生物' | '國文' | '英文'

export const NOTE_SUBJECTS: NoteSubject[] = ['化學', '生物', '國文', '英文']

export type NoteCategory = '考點筆記' | '快速複習'

// 顯示順序：快速複習在最上面（速查優先、且通常已讀過想快速回顧）。
export const NOTE_CATEGORIES: NoteCategory[] = ['快速複習', '考點筆記']

export const DEFAULT_CATEGORY: NoteCategory = '考點筆記'

export function noteCategory(n: NoteEntry): NoteCategory {
  return n.category ?? DEFAULT_CATEGORY
}

export const NOTES: NoteEntry[] = [
  {
    id: 'chem-mock-1',
    href: '/chem-mock-1',
    title: '第一次模擬考範圍速攻（化學）',
    subject: '化學',
    tags: ['總表'],
    group: '第一次模擬考',
    desc: '模擬考化學範圍地圖：十一章對應哪幾篇筆記、三校 12 年各考幾題、9/6 到 9/26 每天讀哪一篇',
  },
  {
    id: 'periodic-table',
    href: '/periodic-table',
    title: '元素週期表',
    subject: '化學',
    tags: ['基礎-週期表'],
    group: '化學工具',
    desc: '必背速查表、自由練習、完整互動週期表（電子組態、電負度/半徑/游離能熱圖）',
  },
  {
    id: 'amino-acids',
    href: '/amino-acids',
    title: '20 種胺基酸',
    subject: '化學',
    tags: ['基礎-胺基酸'],
    group: '化學工具',
    desc: '五大分類、側鏈結構圖、必需胺基酸、簡寫對照',
  },
  {
    id: 'chem-atomic-theory',
    href: '/chem-atomic-theory',
    title: '學說與理論',
    subject: '化學',
    tags: ['基礎-原子結構'],
    group: '基礎化學',
    desc: '原子模型演進（湯木生→密立根→拉塞福→莫色勒→質譜儀）、五大定律＋坎尼札洛、次原子粒子、同位素／同素異形體／異構物',
  },
  {
    id: 'chem-units',
    href: '/chem-units',
    title: '化學上重要的單位',
    subject: '化學',
    tags: ['基礎-單位因次'],
    group: '基礎化學',
    desc: '莫耳/amu/莫耳質量、unit factor、長度/壓力/溫度/能量/濃度、化學常用數學、有效數字',
  },
  {
    id: 'chem-molecules',
    href: '/chem-molecules',
    title: '化學分子表達',
    subject: '化學',
    tags: ['基礎-化學鍵'],
    group: '基礎化學',
    desc: 'AXₙEₘ 與八隅體電子數公式、VSEPR 形狀/鍵角、σ/π 鍵、極性、氫化物/含氧酸/自由基/官能基',
  },
  {
    id: 'chem-stoichiometry',
    href: '/chem-stoichiometry',
    title: '化學反應方程式與化學計量',
    subject: '化學',
    tags: ['基礎-化學計量'],
    group: '基礎化學',
    desc: '平衡（觀察法）、係數比意義、計量總流程、限量試劑、理論產量、產率、原子經濟性',
  },
  {
    id: 'chem-thermo',
    href: '/chem-thermo',
    title: '熱力學',
    subject: '化學',
    tags: ['基礎-熱力學'],
    group: '基礎化學',
    desc: '自發性、熵與亂度、系統/外界/宇宙熵（第二定律）、ΔH·ΔS 四種組合與臨界溫度',
  },
  {
    id: 'chem-quantum',
    href: '/chem-quantum',
    title: '光電效應與量子論：黑體輻射、電磁輻射模型、物質波',
    subject: '化學',
    tags: ['量子力學'],
    group: '量子論與原子結構',
    desc: '黑體輻射(只看溫度)與能量量子化、波動模型 c=νλ、光電效應(E_K=hν−Φ、低限頻率、功函數圖)、電磁波譜與化學用途、德布羅意物質波、波粒二象性與測不準',
  },
  {
    id: 'chem-atomic-spectra',
    href: '/chem-atomic-spectra',
    title: '原子光譜與波耳模型',
    subject: '化學',
    tags: ['原子光譜'],
    group: '量子論與原子結構',
    desc: '連續/線/吸收光譜、焰色試驗(IA/IIA)、氫原子發射光譜與五大系列、能量-頻率-波長計算(H 與類氫 Z²)、波耳能階與軌道半徑',
  },
  {
    id: 'chem-orbitals',
    href: '/chem-orbitals',
    title: '量子力學與原子軌域',
    subject: '化學',
    tags: ['原子軌域'],
    group: '量子論與原子結構',
    desc: '一維/三維盒中質點與零點能量、氫原子波函數與軌域、s/p/d/f 形狀與節點(n−ℓ−1、ℓ)、徑向分布函數、四個量子數與 Pauli',
  },
  {
    id: 'chem-electron-config',
    href: '/chem-electron-config',
    title: '原子軌域能階與電子組態',
    subject: '化學',
    tags: ['電子組態'],
    group: '量子論與原子結構',
    desc: '單/多電子軌域能階(n、n+l、穿透遮蔽)、填電子三大規則與基態激發態、電中性原子組態、第四週期 A 族與過渡金屬(Cr/Cu 例外)、電子組態通式',
  },
  {
    id: 'chem-ions-magnetism',
    href: '/chem-ions-magnetism',
    title: '帶電離子的電子組態與磁光行為',
    subject: '化學',
    tags: ['離子與電子行為'],
    group: '量子論與原子結構',
    desc: '陽/陰離子組態、特殊 A 族惰性電子對效應與假惰性氣體組態、等電子、過渡金屬陽離子與氧化態、順磁反磁、螢光與磷光',
  },
  {
    id: 'chem-periodicity',
    href: '/chem-periodicity',
    title: '週期表與週期性',
    subject: '化學',
    tags: ['週期性'],
    group: '量子論與原子結構',
    desc: '週期表結構與元素分類、各週期填入的軌域、金屬與非金屬性、有效核電荷 Zeff、游離能定義與逐步游離能、週期趨勢與 Be→B/N→O 兩個例外',
  },
  {
    id: 'chem-periodic-trends',
    href: '/chem-periodic-trends',
    title: '週期性趨勢：原子半徑、電子親和力與電負度',
    subject: '化學',
    tags: ['週期趨勢'],
    group: '量子論與原子結構',
    desc: '原子半徑（A 族與過渡金屬、鑭系收縮、波耳半徑）、電子親和力（正負符號與三例外）、離子半徑四結論、電負度趨勢，以及 Zeff／IE／EA／電負度綜合複習與週期性綜合考題',
  },
  {
    id: 'chem-chemical-bonding',
    href: '/chem-chemical-bonding',
    title: '化學鍵與分子結構',
    subject: '化學',
    tags: ['基礎-化學鍵'],
    group: '化學鍵與分子結構',
    desc: '離子化合物、多原子離子、Lewis 結構、形式電荷、共振、混成、VSEPR、分子偶極與分子間作用力',
  },
  {
    id: 'chem-mo-theory',
    href: '/chem-mo-theory',
    title: '分子軌域理論與鍵的性質',
    subject: '化學',
    tags: ['基礎-化學鍵'],
    group: '化學鍵與分子結構',
    desc: '成鍵與反鍵軌域、鍵級、第二週期兩套能階順序、順磁反磁與離子系列、異核與等電子、共軛 π 能階、鍵能鍵長鍵角',
  },
  {
    id: 'chem-coordination',
    href: '/chem-coordination',
    title: '配位化學',
    subject: '化學',
    tags: ['配位化合物'],
    group: '化學鍵與分子結構',
    desc: '配位基與螯合、命名、幾何與異構、氨水先沉澱後溶解、形成常數、價鍵理論、晶場分裂與高低自旋、顏色、生物體內的配位',
  },
  {
    id: 'chem-org-structure',
    href: '/chem-org-structure',
    title: '有機分子的結構與反應中間物',
    subject: '化學',
    tags: ['有機基礎'],
    group: '有機化學基礎',
    desc: '碳的混成與鍵參數、丙二烯與共平面判斷、碳陽離子／碳陰離子／自由基／卡賓、骨架式與不飽和度',
  },
  {
    id: 'chem-org-resonance',
    href: '/chem-org-resonance',
    title: '共振、超共軛與芳香性',
    subject: '化學',
    tags: ['有機基礎'],
    group: '有機化學基礎',
    desc: '共振式與彎箭頭、貢獻度判準、共振對鍵長／穩定度／酸鹼性的影響、超共軛、Hückel 規則與芳香三分法、雜環的 π 電子計數',
  },
  {
    id: 'chem-macromolecules',
    href: '/chem-macromolecules',
    title: '聚合物與生物大分子',
    subject: '化學',
    tags: ['有機基礎'],
    group: '有機化學基礎',
    desc: '加成／縮合／開環聚合的判別、常見聚合物與橡膠、單醣環化與醣苷鍵、肽鍵、核苷酸與磷酸二酯鍵、三種生物大分子都是縮合聚合',
  },
  {
    id: 'chem-org-acid-base',
    href: '/chem-org-acid-base',
    title: '有機酸鹼',
    subject: '化學',
    tags: ['有機基礎'],
    group: '有機化學基礎',
    desc: 'pKa 這把尺、影響酸性的 ARIO 四因素與衝突順序、胺與雜環的鹼性、胺基酸的兩性離子與等電點、判斷反應方向、酸鹼萃取分離',
  },
  {
    id: 'chem-org-nomenclature',
    href: '/chem-org-nomenclature',
    title: '有機命名與官能基',
    subject: '化學',
    tags: ['有機命名與官能基'],
    group: '有機化學基礎',
    desc: '官能基總表與優先順序、IUPAC 主鏈與編號、取代基字母序與俗名、環烷與烯炔、苯環與雜環名稱、順反與 E/Z、構造異構物數目、官能基化學鑑別',
  },
  {
    id: 'chem-stereochem',
    href: '/chem-stereochem',
    title: '立體化學與構形分析',
    subject: '化學',
    tags: ['立體化學'],
    group: '有機化學基礎',
    desc: '異構物分類、對掌中心與掌性判定、CIP 與 R/S、Fischer 投影、對映與非對映與內消旋、比旋光度與 ee、Newman 投影與丁烷構形、環張力與椅式直立平伏、反應的立體化學結果',
  },
  {
    id: 'chem-alkyl-halides',
    href: '/chem-alkyl-halides',
    title: '鹵烷：取代與脫去反應',
    subject: '化學',
    tags: ['有機反應與機構'],
    group: '有機化學基礎',
    desc: '鹵烷級數與 C–X 鍵、自由基鹵化與 NBS 烯丙位溴化、SN2 與 SN1 的速率與立體結果、E2 反式共平面與立體專一、Zaitsev 與 Hofmann、親核性與離去基排序、四條路徑判斷、Grignard 試劑與羧化',
  },
  {
    id: 'chem-spectroscopy',
    href: '/chem-spectroscopy',
    title: '結構鑑定：質譜、紅外光譜、核磁共振',
    subject: '化學',
    tags: ['光譜分析'],
    group: '化學物質的結構資訊',
    desc: '四種光譜工具的分工與電磁波順序、質譜分子離子與同位素峰與三種碎裂、IR 特徵波數與 C=O 位移規則、¹H NMR 訊號數與積分與裂分、¹³C 訊號數、UV-Vis 共軛與互補色、由數據推結構',
  },
  {
    id: 'chem-solution-reactions',
    href: '/chem-solution-reactions',
    title: '溶液中的化學反應',
    subject: '化學',
    tags: ['氧化還原'],
    group: '溶液中的化學反應',
    desc: '電解質與淨離子方程式、溶解度規則與沉澱判斷、酸鹼三套定義與中和、碳酸鹽遇酸、氧化數與例外、氧化劑還原劑與活性序列、半反應法配平、莫耳濃度與稀釋、酸鹼與氧化還原滴定計量',
  },
  {
    id: 'chem-kinetics',
    href: '/chem-kinetics',
    title: '化學動力學',
    subject: '化學',
    tags: ['反應速率'],
    group: '化學動力學與核化學',
    desc: '反應速率與係數換算、速率定律與初速率法、k 的單位反推級數、零一二級積分式與半衰期與作圖、Arrhenius 兩點式、位能圖與活化能、反應機構與速率決定步驟、催化',
  },
  {
    id: 'chem-nuclear',
    href: '/chem-nuclear',
    title: '核化學',
    subject: '化學',
    tags: ['化學綜合'],
    group: '化學動力學與核化學',
    desc: '核種記法與核反應式配平、五種衰變與穿透力、由 n/p 比判斷衰變路線、半衰期與活度計算、放射性定年、質量虧損與結合能、核分裂與核融合、醫用同位素與輻射劑量單位',
  },
  {
    id: 'chem-equilibrium',
    href: '/chem-equilibrium',
    title: '化學平衡',
    subject: '化學',
    tags: ['化學平衡'],
    group: '化學平衡與酸鹼',
    desc: '動態平衡與平衡常數的寫法、K 的代數操作、Kc 與 Kp 換算、反應商 Q 判方向、ICE 表與近似、勒沙特列原理各種擾動、K 與溫度及標準自由能',
  },
  {
    id: 'chem-acid-base-eq',
    href: '/chem-acid-base-eq',
    title: '酸鹼平衡：pH、緩衝液與滴定',
    subject: '化學',
    tags: ['酸鹼平衡', '水溶液離子平衡'],
    group: '化學平衡與酸鹼',
    desc: '水的自解離與 pH、強酸強鹼與極稀溶液、弱酸弱鹼 Ka Kb 與解離度、共軛酸鹼對、鹽類水解、多質子酸、緩衝液與 Henderson–Hasselbalch、滴定曲線與指示劑',
  },
  {
    id: 'chem-ksp',
    href: '/chem-ksp',
    title: '溶解度平衡與錯離子',
    subject: '化學',
    tags: ['水溶液離子平衡'],
    group: '化學平衡與酸鹼',
    desc: 'Ksp 與莫耳溶解度互算、同型才能比 Ksp、共同離子與 pH 效應、Q 對 Ksp 判沉澱、選擇性沉澱、錯離子 Kf 提高溶解度、兩性氫氧化物與陽離子分離',
  },
  {
    id: 'chem-colligative',
    href: '/chem-colligative',
    title: '溶液與依數性質',
    subject: '化學',
    tags: ['溶液與依數性質'],
    group: '溶液性質與電化學',
    desc: '溶液形成與溶解熱、溶解度與亨利定律、濃度單位互換、依數性質與凡特荷夫因子、拉午耳定律與蒸氣壓、沸點上升與凝固點下降、滲透壓、由依數性質反推分子量',
  },
  {
    id: 'bio-mock-1',
    href: '/bio-mock-1',
    title: '第一次模擬考範圍速攻（生物）',
    subject: '生物',
    tags: ['總表'],
    group: '第一次模擬考',
    desc: '模擬考生物範圍地圖：十一章對應哪幾篇筆記、三校 12 年各考幾題、9/6 到 9/26 每天讀哪一篇，外加第一章「生命的研究」速查',
  },
  {
    id: 'bio-cell-1',
    href: '/bio-cell-1',
    title: '概論、顯微鏡與原核／真核',
    subject: '生物',
    tags: ['細胞-原核與真核'],
    group: '細胞學',
    desc: '細胞學說與共同特徵、光學／電子／共軛焦顯微鏡與細胞大小、細胞分離、原核 vs 真核與細菌構造（質體、肽聚醣、內共生）',
  },
  {
    id: 'bio-cell-2',
    href: '/bio-cell-2',
    title: '細胞核、內膜系統與能量胞器',
    subject: '生物',
    tags: ['細胞-細胞核與胞器'],
    group: '細胞學',
    desc: '動植物細胞全景、細胞核與核糖體、內膜系統七成員（ER／高基氏體／溶體／液泡）、分泌路徑、粒線體／葉綠體／過氧化體／蛋白酶體',
  },
  {
    id: 'bio-cell-3',
    href: '/bio-cell-3',
    title: '細胞骨架與細胞外連結',
    subject: '生物',
    tags: ['細胞-骨架與連結'],
    group: '細胞學',
    desc: '微管・微絲・中間絲的直徑/組成/功能、中心粒與纖毛鞭毛的 9×3 與 9+2、細胞外基質與整聯蛋白、四種細胞間連結',
  },
  {
    id: 'bio-cell-4',
    href: '/bio-cell-4',
    title: '細胞膜（構造與功能）',
    subject: '生物',
    tags: ['細胞-細胞膜'],
    group: '細胞膜',
    desc: '磷脂雙層與兩性分子、流體鑲嵌模型、膜流動性（飽和／不飽和、鏈長、溫度、膽固醇）、膜蛋白種類分布與六大功能、細胞間辨識、選擇性通透與運輸蛋白',
  },
  {
    id: 'bio-cell-5',
    href: '/bio-cell-5',
    title: '跨膜運輸與囊泡運輸',
    subject: '生物',
    tags: ['細胞-物質運輸'],
    group: '細胞膜',
    desc: '擴散與滲透、張力與質壁分離、促進性擴散與水孔蛋白、鈉鉀幫浦與膜電位、次級主動運輸與共同運輸、胞吞與胞吐',
  },
  {
    id: 'bio-cell-6',
    href: '/bio-cell-6',
    title: '細胞訊號傳遞',
    subject: '生物',
    tags: ['細胞-訊號傳遞'],
    group: '細胞訊號傳遞',
    desc: '訊號傳遞三階段、四類受體（GPCR／RTK／離子通道／細胞內）、Gα 亞型分流、cAMP 與 IP₃／DAG／Ca²⁺、磷酸化級聯與訊號終止、細胞凋亡',
  },
  {
    id: 'bio-chem-1',
    href: '/bio-chem-1',
    title: '生命化學與生物大分子',
    subject: '生物',
    tags: ['生命分子與生物化學'],
    group: '生命化學與大分子',
    desc: '生命的元素與四種鍵結、水的極性與四大性質、pH 與碳酸緩衝、碳骨架與三種異構物、脫水縮合與水解、醣類脂質蛋白質核酸四大類生物大分子的單體、結構層級與判別',
  },
  {
    id: 'bio-energy-1',
    href: '/bio-energy-1',
    title: '酵素與代謝',
    subject: '生物',
    tags: ['酵素'],
    group: '生物能量學',
    desc: '異化與同化代謝、熱力學兩定律、ΔG 與自發性、ATP 水解與能量偶合、活化能與活性部位、溫度 pH 受質濃度、Km 與 Vmax、四種抑制、異位調控與回饋抑制、酶原',
  },
  {
    id: 'bio-energy-2',
    href: '/bio-energy-2',
    title: '細胞呼吸與光合作用',
    subject: '生物',
    tags: ['細胞呼吸與能量代謝', '光合作用與C4/CAM'],
    group: '生物能量學',
    desc: '有氧呼吸四階段的位置與產物、檸檬酸循環計數、電子傳遞鏈與化學滲透、抑制劑與解偶合劑、ATP 總帳與發酵、β 氧化與糖質新生、葉綠體與光合色素、光系統與線性電子流、卡爾文循環、光呼吸與 C3 C4 CAM 比較',
  },
  {
    id: 'bio-gene-1',
    href: '/bio-gene-1',
    title: '細胞週期、有絲分裂與減數分裂',
    subject: '生物',
    tags: ['細胞分裂'],
    group: '細胞遺傳學',
    desc: '染色體數與 DNA 量的數法、細胞週期分期與三個檢查點、cyclin 與 CDK 與 MPF、有絲分裂五期與紡錘體、動植物胞質分裂與干擾分裂的藥物、減數分裂 I 與 II、聯會與交叉互換、有絲與減數比較、遺傳變異三來源、三種有性生命週期、不分離與非整倍體',
  },
  {
    id: 'bio-gene-2',
    href: '/bio-gene-2',
    title: '孟德爾遺傳與染色體遺傳',
    subject: '生物',
    tags: ['孟德爾遺傳'],
    group: '古典遺傳學',
    desc: '分離律與獨立分配律、棋盤格與機率法則、卡方檢定、顯隱性關係與 ABO 血型、上位與多基因遺傳、譜系與人類單基因疾病、性聯遺傳與巴爾小體、連鎖與圖距、染色體數目與結構異常、印記與母系遺傳、哈溫平衡',
  },
  {
    id: 'bio-mol-1',
    href: '/bio-mol-1',
    title: 'DNA 複製與染色體',
    subject: '生物',
    tags: ['分子遺傳：DNA複製與染色體'],
    group: '分子生物學',
    desc: '轉形與噬菌體實驗、查加夫法則與雙螺旋尺寸、半保留複製的世代計算、複製叉的分子機器與領先延遲股、校對與五種修復、端粒與端粒酶、染色質五層包裝、原核與真核對照、人類基因體組成與 SNP',
  },
  {
    id: 'bio-mol-2',
    href: '/bio-mol-2',
    title: '基因表現：轉錄、轉譯與調控',
    subject: '生物',
    tags: ['基因表現：轉錄轉譯與調控'],
    group: '分子生物學',
    desc: '中心法則與反轉錄、遺傳密碼四性質、轉錄三階段與 TATA 匣、5′ 帽與 poly-A 尾與剪接體、tRNA 擺動與核糖體三位點、訊號胜肽、原核與真核對照、六種突變、乳糖與色胺酸操縱組、真核五層調控與 miRNA',
  },
  {
    id: 'bio-mol-3',
    href: '/bio-mol-3',
    title: '病毒、細菌遺傳與生物技術',
    subject: '生物',
    tags: ['生物技術與分子工具'],
    group: '分子生物學',
    desc: '病毒構造與宿主範圍、噬菌體溶裂與溶源、動物病毒與反轉錄病毒 HIV、類病毒與普里昂、細菌的轉形轉導接合與質體、限制酶與載體與選殖、PCR 與電泳、定序與墨點法與遺傳標記、基因轉殖與 CRISPR 與幹細胞與單株抗體',
  },
  {
    id: 'bio-tissue-1',
    href: '/bio-tissue-1',
    title: '組織與體內恆定',
    subject: '生物',
    tags: ['組織與恆定'],
    group: '動物的形態與功能',
    desc: '四大組織（上皮／結締／肌肉／神經）、上皮的極性與分類、細胞骨架撐起的上皮特化、體內恆定的調控迴路與負回饋、正回饋',
  },
  {
    id: 'bio-circ-1',
    href: '/bio-circ-1',
    title: '循環與呼吸',
    subject: '生物',
    tags: ['循環與呼吸'],
    group: '比較動物生理學',
    desc: '開放式與閉鎖式、單雙循環、鰓的逆流交換與鳥類單向氣流、心臟四腔與瓣膜、心動週期與傳導系統與心電圖、心輸出量與血壓公式、微血管交換與淋巴、血液與凝血、負壓呼吸與肺容積、氧解離曲線與波耳效應、二氧化碳運輸、延腦的調控',
  },
  {
    id: 'bio-immune-1',
    href: '/bio-immune-1',
    title: '免疫系統',
    subject: '生物',
    tags: ['免疫系統'],
    group: '比較動物生理學',
    desc: '先天免疫的屏障與細胞、發炎反應、類鐸受體、補體與干擾素、抗原與淋巴器官、抗原受體與 MHC 與抗原呈現、體液性與細胞性免疫、五類抗體與類型轉換、初次與二次反應、主動與被動免疫與疫苗、過敏四型、自體免疫、HIV、移植與血型',
  },
  {
    id: 'bio-excrete-1',
    href: '/bio-excrete-1',
    title: '排泄與滲透調節',
    subject: '生物',
    tags: ['排泄與滲透調節'],
    group: '比較動物生理學',
    desc: '滲透調節者與順應者、各類動物的水鹽策略、三種含氮廢物、四種排泄構造、腎臟與腎元構造、過濾再吸收分泌排出四步驟與各段小管通透性、逆流倍增與尿素再循環、ADH 與 RAAS 與心房利鈉肽、GFR 與濾過分率與清除率計算',
  },
  {
    id: 'bio-sense-1',
    href: '/bio-sense-1',
    title: '視覺',
    subject: '生物',
    tags: ['視覺'],
    group: '感覺與運動',
    desc: '光線經過的七個構造、眼球壁三層、視網膜分層與兩條路徑、視紫質與光轉導五步、暗亮相反的膜電位、側抑制與接受域、視覺傳導五站與視野缺損、六條眼外肌與瞳孔水晶體的調控',
  },
  {
    id: 'bio-sense-2',
    href: '/bio-sense-2',
    title: '感覺的共同原理與皮膚感覺',
    subject: '生物',
    tags: ['感覺總論'],
    group: '感覺與運動',
    desc: '感覺四步驟與受器電位、刺激強度的頻率編碼、擴增與感覺適應、五類感覺受器、皮膚三層與六種觸壓受器、痛覺與止痛藥、背根神經節與前角、皮節、感覺送到腦的路線',
  },
  {
    id: 'bio-sense-3',
    href: '/bio-sense-3',
    title: '聽覺與平衡覺',
    subject: '生物',
    tags: ['聽覺與平衡覺'],
    group: '感覺與運動',
    desc: '聲音換三次介質、三塊聽小骨、耳蝸三腔室與內外淋巴液的離子差、柯蒂氏器與毛細胞的雙向反應、音量與音調兩套編碼、耳石與半規管、聽小骨的演化',
  },
  {
    id: 'bio-sense-4',
    href: '/bio-sense-4',
    title: '嗅覺與味覺',
    subject: '生物',
    tags: ['嗅覺與味覺'],
    group: '感覺與運動',
    desc: '兩種化學感覺的分工、鼻前與鼻後嗅覺、嗅覺 GPCR 走 cAMP、一千多個 OR 基因與組合編碼、犁鼻器與費洛蒙、五種基本味的受器、味覺轉導與舌頭的三條腦神經',
  },
  {
    id: 'bio-nerve-1',
    href: '/bio-nerve-1',
    title: '十二對腦神經',
    subject: '生物',
    tags: ['腦神經'],
    group: '感覺與運動',
    desc: '腦神經與脊神經的差別、十二對總表、純感覺／純運動／混合三類、腦幹起源 1-1-2-4-4、四對副交感、三對控眼、損傷表現與瞳孔光反射對角膜反射',
  },
  {
    id: 'bio-brain-1',
    href: '/bio-brain-1',
    title: '腦的構造與功能',
    subject: '生物',
    tags: ['腦的構造'],
    group: '感覺與運動',
    desc: '腦的分區與腦幹組成、灰白灰三層、腦室與腦脊髓液的循環、大腦四葉與語言區、邊緣系統、間腦各核、腦幹三段的中樞、小腦與兩種震顫、壓力受器與心血管反射、三種神經傳遞物與帕金森氏症用藥',
  },
  {
    id: 'bio-summary',
    href: '/bio-summary',
    title: '生物・速查總表',
    subject: '生物',
    tags: ['總表'],
    desc: '筆記索引＋細胞學純表格（原核真核／胞器／內膜系統／骨架／連結／動植物／顯微鏡）＋跨篇整合（膜三篇怎麼串、內膜系統接訊號傳遞）',
    category: '快速複習',
  },
  {
    id: 'chem-summary',
    href: '/chem-summary',
    title: '化學・速查總表',
    subject: '化學',
    tags: ['總表'],
    desc: '筆記索引＋公式總表（三種能階模型別搞混、量子論五式同源、Zeff 帶動四趨勢、計量與單位骨架、結構判斷三層順序）',
    category: '快速複習',
  },
  {
    id: 'cn-summary',
    href: '/cn-summary',
    title: '國文・速查總表',
    subject: '國文',
    tags: ['總表'],
    desc: '筆記索引＋查證的權威分工（字義查重編、讀音查簡編）＋字的三層判讀順序與韻文共通框架',
    category: '快速複習',
  },
  {
    id: 'en-summary',
    href: '/en-summary',
    title: '英文・速查總表',
    subject: '英文',
    tags: ['總表'],
    desc: '筆記索引＋三條字彙路線的分工（字首字根／廣讀／考古題）＋遇到生字的拆解順序與讀文章的取捨',
    category: '快速複習',
  },
  {
    id: 'cn-radicals',
    href: '/cn-radicals',
    title: '部首總表',
    subject: '國文',
    tags: ['部首'],
    group: '字詞基礎',
    desc: '康熙 214 部首一頁速查：部首、讀音、意思、例字，標出變形／難讀／自成／形近部首',
  },
  {
    id: 'cn-word-sense-1',
    href: '/cn-word-sense-1',
    title: '破音字與語助詞：思、適、差',
    subject: '國文',
    tags: ['字義辨析'],
    group: '字詞基礎',
    desc: '《詩經》裡當語助詞的「思」與句首句中句末三個位置、入泮采芹的典故、「適」通謫嫡敵、論語里仁無適無莫、「差」的六個讀音、破音字三步判法',
  },
  {
    id: 'cn-shijing-qiyue',
    href: '/cn-shijing-qiyue',
    title: '詩經・七月',
    subject: '國文',
    tags: ['詩經'],
    group: '韻文',
    desc: '《詩經・豳風・七月》農事詩：夏曆與周曆兩套曆法、七月流火正解，加詩經六義、四家詩等常考重點',
  },
  {
    id: 'practice-t1',
    href: '/practice/T1',
    title: '國文實力測驗 T1',
    subject: '國文',
    tags: ['實力測驗'],
    group: '實力測驗',
    desc: '補習班國文實力測驗第 1 回，50 題線上作答，答錯即顯示正解與原卷詳解',
  },
  {
    id: 'practice-t2',
    href: '/practice/T2',
    title: '國文實力測驗 T2',
    subject: '國文',
    tags: ['實力測驗'],
    group: '實力測驗',
    desc: '補習班國文實力測驗第 2 回，50 題線上作答，答錯即顯示正解與原卷詳解',
  },
  {
    id: 'practice-t3',
    href: '/practice/T3',
    title: '國文實力測驗 T3',
    subject: '國文',
    tags: ['實力測驗'],
    group: '實力測驗',
    desc: '補習班國文實力測驗第 3 回，50 題線上作答，答錯即顯示正解與原卷詳解',
  },
  {
    id: 'practice-t4',
    href: '/practice/T4',
    title: '國文實力測驗 T4',
    subject: '國文',
    tags: ['實力測驗'],
    group: '實力測驗',
    desc: '補習班國文實力測驗第 4 回，50 題線上作答，答錯即顯示正解與原卷詳解',
  },
  {
    id: 'practice-t5',
    href: '/practice/T5',
    title: '國文實力測驗 T5',
    subject: '國文',
    tags: ['實力測驗'],
    group: '實力測驗',
    desc: '補習班國文實力測驗第 5 回，50 題線上作答，答錯即顯示正解與原卷詳解',
  },
  {
    id: 'practice-t6',
    href: '/practice/T6',
    title: '國文實力測驗 T6',
    subject: '國文',
    tags: ['實力測驗'],
    group: '實力測驗',
    desc: '補習班國文實力測驗第 6 回，50 題線上作答，答錯即顯示正解與原卷詳解',
  },
  {
    id: 'practice-t7',
    href: '/practice/T7',
    title: '國文實力測驗 T7',
    subject: '國文',
    tags: ['實力測驗'],
    group: '實力測驗',
    desc: '補習班國文實力測驗第 7 回，50 題線上作答，答錯即顯示正解與原卷詳解',
  },
  {
    id: 'practice-t8',
    href: '/practice/T8',
    title: '國文實力測驗 T8',
    subject: '國文',
    tags: ['實力測驗'],
    group: '實力測驗',
    desc: '補習班國文實力測驗第 8 回，50 題線上作答，答錯即顯示正解與原卷詳解',
  },
  {
    id: 'practice-t9',
    href: '/practice/T9',
    title: '國文實力測驗 T9',
    subject: '國文',
    tags: ['實力測驗'],
    group: '實力測驗',
    desc: '補習班國文實力測驗第 9 回，50 題線上作答，答錯即顯示正解與原卷詳解',
  },
  {
    id: 'practice-t10',
    href: '/practice/T10',
    title: '國文實力測驗 T10',
    subject: '國文',
    tags: ['實力測驗'],
    group: '實力測驗',
    desc: '補習班國文實力測驗第 10 回，50 題線上作答，答錯即顯示正解與原卷詳解',
  },
  {
    id: 'practice-t11',
    href: '/practice/T11',
    title: '國文實力測驗 T11',
    subject: '國文',
    tags: ['實力測驗'],
    group: '實力測驗',
    desc: '補習班國文實力測驗第 11 回，50 題線上作答，答錯即顯示正解與原卷詳解',
  },
  {
    id: 'practice-t12',
    href: '/practice/T12',
    title: '國文實力測驗 T12',
    subject: '國文',
    tags: ['實力測驗'],
    group: '實力測驗',
    desc: '補習班國文實力測驗第 12 回，50 題線上作答，答錯即顯示正解與原卷詳解',
  },
  {
    id: 'cn-sima-jizhu',
    href: '/cn-sima-jizhu',
    title: '司馬季主論卜',
    subject: '國文',
    tags: ['古文觀止'],
    group: '古文',
    desc: '劉基《郁離子》寓言體論說文：東陵侯與司馬季主的對話、三段原文與語譯、六組今昔對照的排比與對比、天道親德與鬼神因人而靈、何……為句式',
  },
  {
    id: 'reading-r1',
    href: '/readings/r1',
    title: '增補廣讀 R1：VOA 字彙',
    subject: '英文',
    tags: ['廣讀'],
    desc: '7 篇 VOA 中級文章 + 47 個重點字彙（旋元佑老師編授）',
  },
  {
    id: 'reading-r2',
    href: '/readings/r2',
    title: '增補廣讀 R2：VOA 字彙',
    subject: '英文',
    tags: ['廣讀'],
    desc: '4 篇 VOA 進階短篇小說 + 26 個重點字彙（旋元佑老師編授）',
  },
  {
    id: 'reading-r3',
    href: '/readings/r3',
    title: '增補廣讀 R3：BBC Travel 字彙',
    subject: '英文',
    tags: ['廣讀'],
    desc: '4 篇 BBC Travel 旅遊報導 + 320 個重點字彙（旋元佑老師編授）',
  },
  {
    id: 'reading-r4',
    href: '/readings/r4',
    title: '增補廣讀 R4：CNN 字彙',
    subject: '英文',
    tags: ['廣讀'],
    desc: '3 篇 CNN 國際新聞 + 313 個重點字彙（旋元佑老師編授）',
  },
  {
    id: 'reading-r5',
    href: '/readings/r5',
    title: '增補廣讀 R5：Popular Science 字彙',
    subject: '英文',
    tags: ['廣讀'],
    desc: '4 篇 Popular Science 科普報導 + 307 個重點字彙（旋元佑老師編授）',
  },
]

/** 某分類底下、某科目的筆記（分類省略視為「考點筆記」）。 */
export function notesIn(category: NoteCategory, subject: NoteSubject): NoteEntry[] {
  return NOTES.filter((n) => noteCategory(n) === category && n.subject === subject)
}

/** 一科一份的速查總表（category＝快速複習）。寫完新筆記要回去更新它——由 notes.test.ts 守。 */
export function subjectSummary(subject: NoteSubject): NoteEntry | undefined {
  return NOTES.find((n) => n.subject === subject && noteCategory(n) === '快速複習')
}

/** 某分類＋科目下，依 group 分組（保 NOTES 順序）；無 group 者歸在 key '' 之下。 */
export function noteGroupsIn(
  category: NoteCategory,
  subject: NoteSubject,
): { group: string; notes: NoteEntry[] }[] {
  const order: string[] = []
  const map = new Map<string, NoteEntry[]>()
  for (const n of notesIn(category, subject)) {
    const g = n.group ?? ''
    const arr = map.get(g)
    if (arr) {
      arr.push(n)
    } else {
      map.set(g, [n])
      order.push(g)
    }
  }
  return order.map((g) => ({ group: g, notes: map.get(g) ?? [] }))
}

/** 依 href 找出當前筆記與其「同分類同科目」的上一篇/下一篇（依 NOTES 排序＝閱讀順序）。 */
export function siblingNotes(href: string): {
  current?: NoteEntry
  prev?: NoteEntry
  next?: NoteEntry
} {
  const current = NOTES.find((n) => n.href === href)
  if (!current) return {}
  const group = notesIn(noteCategory(current), current.subject)
  const i = group.findIndex((n) => n.id === current.id)
  return { current, prev: group[i - 1], next: group[i + 1] }
}
